# Generated by Django 5.1.2 on 2024-10-26 10:13

import station.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0006_alter_ticket_options_alter_ticket_journey"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.movie_image_file_path
            ),
        ),
    ]
